### ISSUE TITLE
On Debian dockcheck thinks every running container has an update, and tries to update them

### ISSUE THREAD

**Issue by theAlevan** [mag37/dockcheck#100] opened 2024-10-05 13:57 UTC
I have machines installed with Ubuntu 24.04 and Debian (12.7.0). 
On Ubuntu, running dockcheck.sh works correctly.
On Debian, running dockcheck.sh checks each container, then outputs, that every container has an update. If told so, then it starts to pull each image, then, after failing as the container is running on the latest version, goes to the next container.

For example:
![image](https://github.com/user-attachments/assets/7f2c3968-3941-44ad-8e0e-31b128d483d2)
None of the containers listed here has an image update available.

**Comment by mag37** [comment] 2024-10-05 16:44
That's odd!
I just tested in my Debian 12 LXC and it works fine on my end.
Upgraded successfully through dockcheck.sh, then ran again without finding updates.

Are you using Portainer or other helper-tools?
Or having a different setup than just plain docker-compose?

**Comment by theAlevan** [comment] 2024-10-06 09:23
These are Vannilla Debian, installed on bare metal, just two days ago, with only minor customisation (hostname/network, and installed docker engine). The configuration is almost the same with the Ubuntu machines, the exception being, that I had to manually create the **~/.local/bin/** directory.

All my compose files are deployed manually, using docker CLI (docker compose up). I'm not using any external helpers, except dockcheck for updating them.

**Comment by mag37** [comment] 2024-10-06 11:36
I cant reproduce it. 
Running Debian 12.7 in a VM right now with docker compose, just updated and working fine.

What output do you get if you run tthis on 1 of your containers that report updates available while it shouldn't:   
- Stand in the same directory where you have `regctl` if you dont have it in $PATH.
- Just write your contianer name instead of the **ReplaceThis** on the first line
```bash
ContainerName=ReplaceThis
RepoUrl=$(docker inspect "$ContainerName" --format='{{.Config.Image}}')
docker image inspect "$RepoUrl" --format '{{.RepoDigests}}'
regctl image digest --list "$RepoUrl"
```

**Comment by theAlevan** [comment] 2024-10-06 14:20
dozzle:
[amir20/dozzle@sha256:aa9ea440a33c45fb25d59e06cb6850e6655404fad4bebac6345d8535b9d8a9ee]
WARN[0000] Changing login password for registry          host=index.docker.io
WARN[0000] Changing credential host for registry         host=index.docker.io new="https://index.docker.io/v1/refresh-token" orig="https://index.docker.io/v1/access-token"
sha256:aa9ea440a33c45fb25d59e06cb6850e6655404fad4bebac6345d8535b9d8a9ee

freshrss:
[lscr.io/linuxserver/freshrss@sha256:075c79de60a0651496e3234ffc3a4d39fe4b8ab76060ea2872febf214c39acda]
WARN[0000] Changing login password for registry          host=index.docker.io
WARN[0000] Changing credential host for registry         host=index.docker.io new="https://index.docker.io/v1/refresh-token" orig="https://index.docker.io/v1/access-token"
sha256:075c79de60a0651496e3234ffc3a4d39fe4b8ab76060ea2872febf214c39acda

**Comment by mag37** [comment] 2024-10-06 14:39
Oh there we go.
I might need to so some sanitation to only grab the hash from the output - but I wonder why it's giving you that warning.

Would you mind pasting one of the compose-files? I'll try to debug this further tonight.

**Comment by theAlevan** [comment] 2024-10-07 16:22
Here is a docker compose file for the dozzle container:

`---
services:
  dozzle:
    container_name: dozzle
    environment:
      - TZ=Europe/Bucharest
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock`

**Comment by mag37** [comment] 2024-10-07 18:21
Thank you. Looks very plain, nothing special.. 
So.. I just went through these steps:
- Installed a fresh Debian 12.7 machine (VM)
- Installed Docker from their [docs](https://docs.docker.com/engine/install/debian/#install-using-the-repository)
- Used your `docker-compose.yml` example:
```yml
---
services:
  dozzle:
    container_name: dozzle
    environment:
      - TZ=Europe/Bucharest
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
- Started the container: `docker compose up -d` 
- Installed `dockcheck.sh` 
    - `curl -L https://raw.githubusercontent.com/mag37/dockcheck/main/dockcheck.sh -o ./dockcheck.sh`
    - `chmod +x ./dockcheck.sh`

- Ran the script: `./dockcheck.sh`

**And it works**! No warnings at all - I'm sorry I cant reproduce it.

A workaround that might work for you (and if it do I'll implement it in the script):

On line 252 (currently, might change with future updates):
`  if RegHash=$(${t_out} $regbin image digest --list "$RepoUrl" 2>&1) ; then`
Add `-v error` between *$regbin* and *image*, like this:
`  if RegHash=$(${t_out} $regbin -v error image digest --list "$RepoUrl" 2>&1) ; then`

That would make it ignore the warnings, hopefully, and the hash-check should work as usual.
Let me know if that works for you.

**Comment by theAlevan** [comment] 2024-10-07 19:39
It works! Thank you!

**Comment by mag37** [comment] 2024-10-08 07:43
Still no clue what's causing the issue :( but I'll close this as solved and add it to the patch I'm currently working on.

**Closed by mag37** 2024-10-08 07:43 UTC

**Comment by Wyall** [comment] 2024-10-13 09:56
Just FYI: I had the same problem on Ubuntu 22.04 and the change in 252 fixed it.

**Comment by mag37** [comment] 2024-10-13 13:08
> Just FYI: I had the same problem on Ubuntu 22.04 and the change in 252 fixed it.

Thank you for the info. Glad the workaround fixed it, but I dont understand the initial error and that frustrates me 😅

**Comment by Wyall** [comment] 2024-10-13 13:13
Can I help you in any way? As you tried to reproduce it, I thought what I possibly changed after the docker installation and the only thing that comes to mind is that I don't run it as superuser, i.e. I ran
`sudo groupadd docker
sudo usermod -aG docker USERNAME`
That's it I think.

**Comment by mag37** [comment] 2024-10-13 13:41
Thank you but I don't really know. It's regctl throwing the errors. 

Are you using any private registry-settings or custom auth for specific repos on docker hub or anythins similar? Otherwise I'm clueless I'm afraid :)

**Comment by Wyall** [comment] 2024-10-13 14:31
Not intentionally, no.
