### ISSUE TITLE
[FEATURE REQUEST] Telegram notification

### ISSUE THREAD

**Issue by JoyZzzzz** [mag37/dockcheck#71] opened 2024-02-19 02:28 UTC
Is it possible to add an optional option to the notify_telegram.sh template to send a message not only to chat, but also to a specific chat topic?
The "message_thread_id" parameter is responsible for this.

**Comment by mag37** [comment] 2024-02-19 19:58
It should be possible with just adding `message_thread_id` to the TelegramData field. 
Something like:
```
TelegramTopicID=12345678
TelegramData="{\"chat_id\":\"$TelegramChatId\",\"text\":\"$MessageBody\",\"message_thread_id\":\"$TelegramTopicID\",\"disable_notification\": false}"
```

The templates are just there as suggestions :) If you test this and it works as intended, I'll add it to the template. 
I might try it out later myself - just don't have a chat+thread to experiment with right now.

**Comment by JoyZzzzz** [comment] 2024-02-23 11:22
`TelegramTopicID="Your Telegram Chat TopicID here or 0"
 TelegramData="{\"chat_id\":\"$TelegramChatId\",\"message_thread_id\":\"$TelegramTopicID\",\"text\":\"$MessageBody\",\"disable_notification\": false}"`

**Comment by JoyZzzzz** [comment] 2024-02-23 11:26
Yes it works
` TelegramTopicID="Your Telegram Chat TopicID here or 0"`

**Comment by mag37** [comment] 2024-03-27 20:52
Edited and added to main branch. Thank you for the suggestion!
Closing.

**Closed by mag37** 2024-03-27 20:52 UTC
